- README.md
- package.json
Joi has just published version 10.0.1.
Since you are using peer dependencies, the package.json had to be changed to be continue to use celebrate with the new Joi version.
I have made the changed and run the tests. Everything passed.
I also changed the version to 4.0.0 because of the compatibility break.
> Joi versions 10.x.x

- lib/index.js
- test/__snapshots__/celebrate.test.js.snap
- test/celebrate.test.js
- `node` version - 6
- `celebrate` version - 4.0.3
- `joi` version (via `npm ls --depth=0 | grep joi`) - 10.6.0
The issue I am having with `celebrate` is:
I am working on an application that uses Joi for other validation as well as using celebrate. When next is called with any Joi error, the celebrate error handler intercepts it, and if it is not from celebrate it throws the following error:.
```
TypeError: Cannot read property 'source' of undefined
at /usr/src/app/node_modules/celebrate/lib/index.js:71:28
```
The celebrate errors middleware should ignore any errors not from celebrate, so maybe as well as setting `err._meta = { source }` it should set `err._isCelebrate = true` and use this instead of `err.isJoi`?
Will happily raise a PR if you agree with this approach.
- Add "isCelebrate" …
> Don't handle Joi errors that are not generated by celebrate

- README.md
- lib/index.d.ts
- lib/index.js
- test/celebrate.test.js
- test/integration.test.js
Closes #46
Change the exports to be an object with APIs attached to it, rather than just a function.
> API refactor

- README.md
- lib/index.js
- test/__snapshots__/celebrate.test.js.snap
- test/celebrate.test.js
Closes #51
Expose an "isCelebrate" method to allow custom error middleware handlers a reliable way to check
to see if in incomming error came from celebrate or not.
> Added isCelebrate

- lib/index.d.ts
- package.json
Closes #56
Type the exported Joi object to as a @types/joi object. Pin the version as it's
technically for version 13 of Joi, but at moment, 12 and 13 have the same
exported API. This will probably change in the future.
> Strongly type Joi export

- benchmarks/index.js
- lib/index.js
- package.json
Added some benchmarking tooling to have an idea of how changes affect
performance 
Moved code around to allow for more constant values and fewer memory
allocations 
Switch to non-callback validation function to remove extra closure
We may want to log the benchmarks to see how that look over time or across different node versions...
```
valid x 28,130 ops/sec ±1.68% (85 runs sampled)
invalid x 16,185 ops/sec ±1.85% (85 runs sampled)
```
This run was with these changes on node 6
Previous run before changes
```
valid x 27,035 ops/sec ±1.02% (82 runs sampled)
invalid x 15,341 ops/sec ±1.72% (80 runs sampled)
```
> Perf updates

- benchmarks/index.js
- lib/index.js
- package.json
Closes #80
Closes #83
Removed fast-series and just did things using native loops and no callbacks. Saw
about a 1000 ops per second speed improvement. Dropped conditional setting of `req.*` values
and just always use `Object.defineProperty`.
> Code Cleanup and optimizations

- lib/index.d.ts
The `errors` function is *not* an `ErrorRequestHandler` middleware function, but rather *returns* the `ErrorRequestHandler` middleware function.
As a result, when passing `errors` to `Application.use`, you're unable to call it and forced to just provide the function itself.  This in turn creates an infinite loop as the middleware factory never calls `next`.
This change fixes that issue and allows you to provide `errors()` to `Application.use`.
> Fixed errors Middleware Typing

- lib/index.d.ts
This PR updates the `errors` function type definition to more accurately follow the actual implementation and fix typescript lint errors.
> Update errors() typedef

- README.md
- lib/constants.js
- lib/index.d.ts
- lib/index.js
- package-lock.json
- package.json
- test/__snapshots__/celebrate.test.js.snap
- test/celebrate.test.js
- test/integration.test.js
Closes #139
Change the arguments to format() to accomodate both sync and async validations.
Also exposed `Segments` enum to help consumers and docs.
> Update format + exposes Segments

- README.md
- lib/index.d.ts
- lib/index.js
- test/__snapshots__/celebrate.test.js.snap
- test/celebrate.test.js
Closes #138
We now use error objects that extend the base `Error` object. Removed
`format` in favor of calling `CelebrateError()` directly. This way we
are always using "real" Error objects. This can be handy for things
outside of this library that want all Error objects to extend the
built in one.
> Use CelebrateError object instead of POJO

- lib/index.d.ts
Removed namespace, fixed type definitions, applied some TSLint, separated celebrate() options in their own interfaces, fixed CelebrateError definition.
> Removed namespace

- README.md
- lib/index.d.ts
- lib/index.js
- lib/schema.js
- test/celebrate.test.js
After staring at the main validation path for a few hours, I realized a lot of this code is more complex than it really needed to be. 
- Reuse the same array on every request. This way, I'm not creating single use arrays that need to be GCed after every run.
- Stop creating new promises on every validation and instead let Joi do this (I don't think's a real promise, but it behaves like one)
- Change `validateBody` to be a closure to keep a curried copy of `validateSegment` around so we only need to create this once.
- Changed the main validation path to use `[].reduce(() =>{}, Promise.resolve(null)` rather than the recursive way it used to be.
- Precompile all the schemas outside of the middleware so it only happens once per invocation of `celebrate()` not every time the request is …
> New Internals

- .travis.yml
- README.md
- lib/index.d.ts
- lib/index.js
- lib/schema.js
- package.json
- test/__snapshots__/celebrate.test.js.snap
- test/celebrate.test.js
Add a config object argument to `errors()`. Right now, this only
lets users tune the status code response.
Updated engine value and travis test matrix for node 12 and "node" to match what the bundled version of Joi does.
> Error handler config

- README.md
- package.json
Remove `engine` from package.json because it causes more problems than it solves. Also some small cleanup to the README to include a note about `get` requests and HTTP payloads.
> Engine update

- lib/index.d.ts
[Typescript type guards](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards) return a boolean so this is not a breaking change, and the error returned from the express error middleware is typeof `any` not `object`.
> Make isCelebrateError a type guard

- lib/index.d.ts
As RequestHandler in express defined as
`interface RequestHandler<P = core.ParamsDictionary, ResBody = any, ReqBody = any, ReqQuery = core.Query> extends core.RequestHandler<P, ResBody, ReqBody, ReqQuery> { }`
we also have to support parameters
> Add generic celebrate function declaration

- README.md
The API for adding new error details uses the .set method instead of .add
> Fixed CelebrateErrors README example

- lib/celebrate.js
- test/celebrate.test.js
Closes #215
The way _.curryRight doesn't really work like you'd think it would, so I
rewrote it to use _.curry and _.flip so that it now works like the documentation
says it does.
> Fixed celebrator

- LICENSE
- README.md
- lib/CelebrateError.js
- lib/celebrate.js
- lib/schema.js
- test/__snapshots__/celebrate.test.js.snap
- test/celebrate.test.js
Adds additional `message` value to the options argument to `errors()`. Also,
changed the default `message` value of CelebrateError to 'Validation failed'.
> Closes #219

- lib/index.d.ts
Allows using the `import { Joi } from 'celebrate'` to reference Joi types without importing Joi manually.
This is not highly tested, but it seems to do the trick
> Export joi namespace along with const
