- package.json
- test/index.js
Changed dependencies to rely on peerDeps to help improve compatibility.
> Updated Joi to version 9. Closes #7.

- README.md
> Updated README to reflect change to peerDep.

- .gitignore
- lib/index.js
- package.json
- test/index.js
Switched out insync for fastseries for the almost 1900ms performance boost.
Updated devDependencies.
This also had the side benefit of not having to declare `validateSource` on each run.
Not sure how to version this?
> Fastseries

- .github/ISSUE_TEMPLATE.md
- README.md
- lib/index.js
- package.json
- test/index.js
Not sure about the version of this since I technically changed the signature of the error response... Thoughts @cjihrig?
> Error handler update

- .travis.yml
- lib/index.js
- package.json
Three commits:
- Update dependencies (only `code`).
- Add Node 7 to the Travis file.
- Attach the schema to the validation middleware.
> Repo maintenance and expose schema

- .gitignore
- .travis.yml
- lib/index.d.ts
- package.json
> Added type def file.

- lib/index.d.ts
> Enhance TypeScript definitions

- README.md
- lib/index.d.ts
- lib/index.js
- package.json
- test/index.js
Closes #35
Updated joi version to 11. Made it a formal dependency and also exposed it to
outside consumers to address potential compatibility problems.
> Joi verion 11.

- package.json
> Add 'types' field to package.json

- README.md
- lib/index.js
- package.json
- test/index.js
Closes #38 
A test is not passing, but since it was not passing before I guess this is normal
That's a small pull request, but well, I saw an issue...
It's an occasion for me to thank you for your work, celebrate is great :smile:
> updated joi to version 12

- .travis.yml
- README.md
- lib/index.js
- package.json
- test/__snapshots__/integration.test.js.snap
- test/integration.test.js
Closes #45
Adds integration tests aginst actual running express servers.
Adds some additional logic to set the validated values back to req.
> Integration tests

- .eslintrc.js
- README.md
- lib/index.js
- lib/schema.js
- package.json
- test/celebrate.test.js
- test/integration.test.js
Closes #68
Migrated to the airbnb eslint settings. Updated package.json scripts. Updated
README to include sweet new badge. Also did a pass of fixes with new eslint
settings
> eslint migration

- README.md
- jest.config.js
Closes #75
Added new logo file and updated README
Added sponsorship link as well
> Sponsorship and New Logo

- package.json
- test/__snapshots__/celebrate.test.js.snap
- test/celebrate.test.js
Closes #81
Migrated to jest 23. Updated a bunch of tests to use describe.each
> Upgrade jest

- .travis.yml
- jest.config.js
- package.json
- test/celebrate.test.js
Closes #95, #93, #92
Updated travis to use latest and stable express. Set node as the jest testing
environment. Updated joi type defs. Used faker in tests to indicate that values
aren't important, just have to be something.
> Small Cleannups

- .gitignore
- .travis.yml
- README.md
- jest.config.js
- lib/index.d.ts
- lib/index.js
- lib/schema.js
- package-lock.json
- package.json
- test/__snapshots__/integration.test.js.snap
- test/celebrate.test.js
- test/integration.test.js
Closes #100
Added new option to `celebrate` to pass in `celebrate` specific options. Updated
tests. Updated README. Cleaned up more type definitions.
> Request Context

- lib/index.d.ts
- package-lock.json
- package.json
> Use namespaced joi type defs

- README.md
- lib/index.d.ts
- lib/index.js
- lib/schema.js
- package-lock.json
- package.json
- test/__snapshots__/celebrate.test.js.snap
- test/celebrate.test.js
Closes #118
Adds a format function that can be used to format any Joi error to the same
shape as errors coming from the `celebrate` middleware.
> Adds format function

- lib/constants.js
- lib/index.js
- lib/schema.js
- package-lock.json
- package.json
- test/__snapshots__/celebrate.test.js.snap
- test/celebrate.test.js
- test/integration.test.js
- utils/benchmark.js
Mega PR
- Updates Joi to 16
- Added `abortEarly` test
> Joi@16 Updates

- .travis.yml
- package-lock.json
- package.json
Bumped some node versions around. Regnerated package-lock with
newer npm.
> Updated Node versions

- lib/index.js
- test/integration.test.js
Fixes #147
In trying to be clever, I ended up introducing a bug where multiple
request would reuse the same Promises, so they wouldn't not run
after the first request.
> Per request `steps`

- README.md
- lib/index.d.ts
- lib/index.js
- test/celebrate.test.js
Closes #155
Use Joi.assert to remove a few lines of code. Also
changed some internal variable names.
> Use Joi.assert

- package.json
> feat: Move @types/hapi__joi to dependencies

- README.md
- lib/index.d.ts
- lib/index.js
- package.json
- test/celebrate.test.js
Introduces `celebrator` which is a curried version of `celebrate`.
> Curried celebrate

- README.md
- lib/CelebrateError.js
- lib/celebrate.js
- lib/constants.js
- lib/index.d.ts
- lib/index.js
- lib/schema.js
- test/__snapshots__/celebrate.test.js.snap
- test/celebrate.test.js
- utils/benchmark.js
Started adding ability to validate the full request object. Still
need to finish fixing failing tests, updating docs.
> Full Validate Implementation

- lib/celebrate.js
- lib/index.d.ts
- lib/index.js
- lib/schema.js
- package.json
- test/__snapshots__/celebrate.test.js.snap
Closes #187
The tests change so this is technically a breaking change.
> Move away from @hapi/joi

- README.md
> Clarify docs for FULL mode
